# Stack for a Celery worker plus an rsync-over-SSH artifact sync sidecar.
# - Uses a named volume `artifacts` mounted at /artifacts in both containers
# - Requires Docker secrets: `rsync_key` and `known_hosts`
# - Optional reverse SSH tunnel sidecar is available via the `tunnel` profile

name: clippyfront-worker

volumes:
  artifacts:
    name: clippyfront_artifacts

secrets:
  rsync_key:
    file: ./secrets/rsync_key
  known_hosts:
    file: ./secrets/known_hosts

services:
  worker:
    image: ${WORKER_IMAGE:-ghcr.io/zebadrabbit/clippy-worker:latest}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ARTIFACTS_DIR=/artifacts
    volumes:
      - artifacts:/artifacts

  # Optional local build of the worker to avoid pulling from GHCR
  # Use with: docker compose -f compose.worker.yaml --profile local up -d --build worker-local artifact-sync
  worker-local:
    profiles: ["local"]
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    image: clippyfront-worker:local
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ARTIFACTS_DIR=/artifacts
    volumes:
      - artifacts:/artifacts

  artifact-sync:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: ${SYNC_IMAGE:-clippyfront-artifact-sync:latest}
    restart: unless-stopped
    depends_on:
      - worker
    env_file:
      - .env
    environment:
      - WORKER_ID=${WORKER_ID}
      - INGEST_HOST=${INGEST_HOST}
      - INGEST_USER=${INGEST_USER}
      - INGEST_PORT=${INGEST_PORT:-22}
      - INGEST_PATH=${INGEST_PATH:-/srv/ingest}
      - PUSH_INTERVAL=${PUSH_INTERVAL:-60}
      - CLEANUP_MODE=${CLEANUP_MODE:-none}
      - ARCHIVE_DIR=${ARCHIVE_DIR:-/artifacts/_pushed}
    volumes:
      - artifacts:/artifacts
    secrets:
      - source: rsync_key
        target: /run/secrets/rsync_key
      - source: known_hosts
        target: /run/secrets/known_hosts

  tunnel:
    # Optional: enable with `--profile tunnel`
    profiles: ["tunnel"]
    image: ghcr.io/jnovack/autossh:latest
    restart: unless-stopped
    env_file:
      - .env
    # Example: set TUNNEL_REVERSE=2222:localhost:22 in your .env
    command: >-
      -M 0 -N -o ServerAliveInterval=30 -o ServerAliveCountMax=3
      -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/run/secrets/known_hosts
      -i /run/secrets/rsync_key
      -R ${TUNNEL_REVERSE}
      ${INGEST_USER}@${INGEST_HOST} -p ${INGEST_PORT:-22}
    secrets:
      - source: rsync_key
        target: /run/secrets/rsync_key
      - source: known_hosts
        target: /run/secrets/known_hosts
