version: "3.8"
services:
  gpu-worker:
    image: clippyfront-gpu-worker:latest
    environment:
      - CELERY_BROKER_URL=redis://VPN_HOST_IP:6379/0
      - CELERY_RESULT_BACKEND=redis://VPN_HOST_IP:6379/0
      - REDIS_URL=redis://VPN_HOST_IP:6379/0
      - DATABASE_URL=postgresql://USER:PASSWORD@VPN_HOST_IP/clippy_front
      - TMPDIR=/app/instance/tmp
    volumes:
      - /mnt/clippy:/app/instance
    deploy: {}
    command: ["celery", "-A", "app.tasks.celery_app", "worker", "-Q", "gpu", "--loglevel=info"]
