"""init migrations and add user.date_format

Revision ID: 084c3bc02dc5
Revises:
Create Date: 2025-10-19 08:30:58.676218

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "084c3bc02dc5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "date_format",
            existing_type=sa.VARCHAR(length=32),
            nullable=False,
            existing_server_default=sa.text("'auto'"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "date_format",
            existing_type=sa.VARCHAR(length=32),
            nullable=True,
            existing_server_default=sa.text("'auto'"),
        )

    # ### end Alembic commands ###
