"""Add music ducking parameters

Revision ID: 20c97f62ef94
Revises: 8a9a6bf1c32e
Create Date: 2025-11-23 20:39:00.530017

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20c97f62ef94"
down_revision = "8a9a6bf1c32e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("duck_threshold", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("duck_ratio", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("duck_attack", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("duck_release", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("duck_release")
        batch_op.drop_column("duck_attack")
        batch_op.drop_column("duck_ratio")
        batch_op.drop_column("duck_threshold")

    # ### end Alembic commands ###
