"""add attribution fields to media_files for music metadata

Revision ID: 25a2658e2742
Revises: 71c2f4043df4
Create Date: 2025-11-27 23:47:15.852897

"""
import os

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "25a2658e2742"
down_revision = "71c2f4043df4"
branch_labels = None
depends_on = None


def upgrade():
    # Get table prefix from environment
    table_prefix = os.environ.get("TABLE_PREFIX", "")
    media_files_table = f"{table_prefix}media_files"

    # ### commands auto generated by Alembic - please adjust! ###
    # Add attribution fields to media_files
    with op.batch_alter_table(media_files_table, schema=None) as batch_op:
        batch_op.add_column(sa.Column("artist", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("album", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("title", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("license", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("attribution_url", sa.String(length=500), nullable=True)
        )
        batch_op.add_column(sa.Column("attribution_text", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # Get table prefix from environment
    table_prefix = os.environ.get("TABLE_PREFIX", "")
    media_files_table = f"{table_prefix}media_files"

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(media_files_table, schema=None) as batch_op:
        batch_op.drop_column("attribution_text")
        batch_op.drop_column("attribution_url")
        batch_op.drop_column("license")
        batch_op.drop_column("title")
        batch_op.drop_column("album")
        batch_op.drop_column("artist")
    # ### end Alembic commands ###
