"""Add discord_channel_id to users table

Revision ID: 30aefd43c223
Revises: deb9cecee237
Create Date: 2025-11-23 17:03:11.857807

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "30aefd43c223"
down_revision = "deb9cecee237"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("discord_channel_id", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "discord_channel_id")
    # ### end Alembic commands ###
