"""Add monthly_price_cents to Tier model

Revision ID: 62197abac220
Revises: 40b6eb8de13d
Create Date: 2025-11-29 03:21:43.138118

"""
import os

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "62197abac220"
down_revision = "40b6eb8de13d"
branch_labels = None
depends_on = None

# Get table prefix from environment
_TABLE_PREFIX = os.environ.get("TABLE_PREFIX", "")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        f"{_TABLE_PREFIX}tiers",
        sa.Column("monthly_price_cents", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(f"{_TABLE_PREFIX}tiers", "monthly_price_cents")
    # ### end Alembic commands ###
