"""Add announcements and dismissed announcements tables

Revision ID: 643de2b99af0
Revises: 20c97f62ef94
Create Date: 2025-11-26 00:17:42.011659

"""
import os

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "643de2b99af0"
down_revision = "20c97f62ef94"
branch_labels = None
depends_on = None


def upgrade():
    # Get table prefix from environment
    table_prefix = os.environ.get("TABLE_PREFIX", "")
    announcements_table = f"{table_prefix}announcements"
    dismissed_table = f"{table_prefix}dismissed_announcements"
    users_table = f"{table_prefix}users"

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        announcements_table,
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "announcement_type",
            sa.Enum("INFO", "SUCCESS", "WARNING", "DANGER", name="announcementtype"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(announcements_table, schema=None) as batch_op:
        batch_op.create_index(
            f"ix_{announcements_table}_active", ["active"], unique=False
        )

    op.create_table(
        dismissed_table,
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("announcement_id", sa.Integer(), nullable=False),
        sa.Column("dismissed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            [f"{announcements_table}.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [f"{users_table}.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "announcement_id", name=f"{table_prefix}uq_user_announcement"
        ),
    )
    with op.batch_alter_table(dismissed_table, schema=None) as batch_op:
        batch_op.create_index(
            f"ix_{dismissed_table}_announcement_id",
            ["announcement_id"],
            unique=False,
        )
        batch_op.create_index(
            f"ix_{dismissed_table}_user_id",
            ["user_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # Get table prefix from environment
    table_prefix = os.environ.get("TABLE_PREFIX", "")
    announcements_table = f"{table_prefix}announcements"
    dismissed_table = f"{table_prefix}dismissed_announcements"

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(dismissed_table, schema=None) as batch_op:
        batch_op.drop_index(f"ix_{dismissed_table}_user_id")
        batch_op.drop_index(f"ix_{dismissed_table}_announcement_id")

    op.drop_table(dismissed_table)
    with op.batch_alter_table(announcements_table, schema=None) as batch_op:
        batch_op.drop_index(f"ix_{announcements_table}_active")

    op.drop_table(announcements_table)
    # ### end Alembic commands ###
