"""Add announcements and dismissed announcements tables

Revision ID: 643de2b99af0
Revises: 20c97f62ef94
Create Date: 2025-11-26 00:17:42.011659

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "643de2b99af0"
down_revision = "20c97f62ef94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dev_announcements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "announcement_type",
            sa.Enum("INFO", "SUCCESS", "WARNING", "DANGER", name="announcementtype"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dev_announcements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dev_announcements_active"), ["active"], unique=False
        )

    op.create_table(
        "dev_dismissed_announcements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("announcement_id", sa.Integer(), nullable=False),
        sa.Column("dismissed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["dev_announcements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["dev_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "announcement_id", name="dev_uq_user_announcement"
        ),
    )
    with op.batch_alter_table("dev_dismissed_announcements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dev_dismissed_announcements_announcement_id"),
            ["announcement_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_dev_dismissed_announcements_user_id"),
            ["user_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dev_dismissed_announcements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dev_dismissed_announcements_user_id"))
        batch_op.drop_index(
            batch_op.f("ix_dev_dismissed_announcements_announcement_id")
        )

    op.drop_table("dev_dismissed_announcements")
    with op.batch_alter_table("dev_announcements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dev_announcements_active"))

    op.drop_table("dev_announcements")
    # ### end Alembic commands ###
