"""Add background music support to projects

Revision ID: 6bc4412d51c7
Revises: 3d7f95146443
Create Date: 2025-11-23 03:04:04.958854

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6bc4412d51c7"
down_revision = "3d7f95146443"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("background_music_id", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("music_volume", sa.Float(), nullable=True))
        batch_op.add_column(
            sa.Column("music_start_mode", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(
            sa.Column("music_end_mode", sa.String(length=20), nullable=True)
        )
        batch_op.create_foreign_key(
            None, "media_files", ["background_music_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("music_end_mode")
        batch_op.drop_column("music_start_mode")
        batch_op.drop_column("music_volume")
        batch_op.drop_column("background_music_id")

    # ### end Alembic commands ###
