"""add vertical_video_zoom and align_vertical_video

Revision ID: 8a9a6bf1c32e
Revises: 30aefd43c223
Create Date: 2025-11-22 18:15:01.669738

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8a9a6bf1c32e"
down_revision = "30aefd43c223"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("vertical_zoom", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("vertical_align", sa.String(length=10), nullable=True)
        )

    # Set default values for existing rows
    op.execute("UPDATE projects SET vertical_zoom = 100 WHERE vertical_zoom IS NULL")
    op.execute(
        "UPDATE projects SET vertical_align = 'center' WHERE vertical_align IS NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("vertical_align")
        batch_op.drop_column("vertical_zoom")
    # ### end Alembic commands ###
