"""Add notification preferences table

Revision ID: f76aa275af46
Revises: 6c0cc1714fed
Create Date: 2025-11-20 21:07:26.060355

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f76aa275af46"
down_revision = "6c0cc1714fed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email_compilation_complete", sa.Boolean(), nullable=False),
        sa.Column("email_compilation_failed", sa.Boolean(), nullable=False),
        sa.Column("email_team_invitation", sa.Boolean(), nullable=False),
        sa.Column("email_team_member_added", sa.Boolean(), nullable=False),
        sa.Column("email_project_shared", sa.Boolean(), nullable=False),
        sa.Column("email_mention", sa.Boolean(), nullable=False),
        sa.Column("email_digest_enabled", sa.Boolean(), nullable=False),
        sa.Column("email_digest_frequency", sa.String(length=20), nullable=False),
        sa.Column("email_digest_time", sa.String(length=5), nullable=False),
        sa.Column("inapp_all_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_logs_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("compilation_tasks", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )
        batch_op.drop_constraint(
            batch_op.f("compilation_tasks_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("notifications_user_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("notifications_team_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("notifications_actor_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("notifications_project_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "projects", ["project_id"], ["id"])
        batch_op.create_foreign_key(None, "users", ["actor_id"], ["id"])
        batch_op.create_foreign_key(None, "teams", ["team_id"], ["id"])
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.alter_column(
            "platform_preset",
            existing_type=postgresql.ENUM(
                "youtube",
                "youtube_shorts",
                "tiktok",
                "instagram_feed",
                "instagram_reel",
                "instagram_story",
                "twitter",
                "facebook",
                "twitch",
                "custom",
                name="platformpreset",
            ),
            type_=sa.Enum(
                "YOUTUBE",
                "YOUTUBE_SHORTS",
                "TIKTOK",
                "INSTAGRAM_FEED",
                "INSTAGRAM_REEL",
                "INSTAGRAM_STORY",
                "TWITTER",
                "FACEBOOK",
                "TWITCH",
                "CUSTOM",
                name="platformpreset",
                native_enum=False,
            ),
            existing_nullable=True,
            existing_server_default=sa.text("'custom'::platformpreset"),
        )

    with op.batch_alter_table("scheduled_tasks", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )
        batch_op.drop_constraint(
            batch_op.f("scheduled_tasks_task_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("scheduled_tasks_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])
        batch_op.create_foreign_key(None, "compilation_tasks", ["task_id"], ["id"])

    with op.batch_alter_table("team_invitations", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("team_invitations_token_key"), type_="unique"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("team_invitations", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("team_invitations_token_key"), ["token"]
        )

    with op.batch_alter_table("scheduled_tasks", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("scheduled_tasks_user_id_fkey"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("scheduled_tasks_task_id_fkey"),
            "compilation_tasks",
            ["task_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.alter_column(
            "platform_preset",
            existing_type=sa.Enum(
                "YOUTUBE",
                "YOUTUBE_SHORTS",
                "TIKTOK",
                "INSTAGRAM_FEED",
                "INSTAGRAM_REEL",
                "INSTAGRAM_STORY",
                "TWITTER",
                "FACEBOOK",
                "TWITCH",
                "CUSTOM",
                name="platformpreset",
                native_enum=False,
            ),
            type_=postgresql.ENUM(
                "youtube",
                "youtube_shorts",
                "tiktok",
                "instagram_feed",
                "instagram_reel",
                "instagram_story",
                "twitter",
                "facebook",
                "twitch",
                "custom",
                name="platformpreset",
            ),
            existing_nullable=True,
            existing_server_default=sa.text("'custom'::platformpreset"),
        )

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("notifications_project_id_fkey"),
            "projects",
            ["project_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("notifications_actor_id_fkey"),
            "users",
            ["actor_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("notifications_team_id_fkey"),
            "teams",
            ["team_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("notifications_user_id_fkey"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("compilation_tasks", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("compilation_tasks_user_id_fkey"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )

    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_logs_created_at"))

    op.drop_table("notification_preferences")
    # ### end Alembic commands ###
