#!/usr/bin/env bash
#
# setup_monitoring.sh - Install and configure Grafana + Prometheus monitoring stack
#
# Usage:
#   Local:  ./setup_monitoring.sh
#   Remote: ./setup_monitoring.sh --remote <host> [--user <username>]
#
# This script is idempotent - safe to run multiple times to update configuration.
#

set -euo pipefail

# ==================== Configuration ====================

# Prometheus settings
PROMETHEUS_VERSION="${PROMETHEUS_VERSION:-2.48.0}"
PROMETHEUS_PORT="${PROMETHEUS_PORT:-9090}"
PROMETHEUS_RETENTION="${PROMETHEUS_RETENTION:-30d}"
PROMETHEUS_SCRAPE_INTERVAL="${PROMETHEUS_SCRAPE_INTERVAL:-15s}"

# Grafana settings
GRAFANA_VERSION="${GRAFANA_VERSION:-10.2.2}"
GRAFANA_PORT="${GRAFANA_PORT:-3000}"
GRAFANA_ADMIN_USER="${GRAFANA_ADMIN_USER:-admin}"
GRAFANA_ADMIN_PASSWORD="${GRAFANA_ADMIN_PASSWORD:-}"  # Will prompt if empty

# Node exporter settings (for system metrics)
NODE_EXPORTER_VERSION="${NODE_EXPORTER_VERSION:-1.7.0}"
NODE_EXPORTER_PORT="${NODE_EXPORTER_PORT:-9100}"

# Application settings
APP_METRICS_PORT="${APP_METRICS_PORT:-5000}"  # Flask app metrics endpoint
REDIS_METRICS_PORT="${REDIS_METRICS_PORT:-6379}"
POSTGRES_EXPORTER_PORT="${POSTGRES_EXPORTER_PORT:-9187}"

# Installation paths
INSTALL_DIR="${INSTALL_DIR:-/opt}"
DATA_DIR="${DATA_DIR:-/var/lib}"
CONFIG_DIR="${CONFIG_DIR:-/etc}"

# Remote execution
REMOTE_HOST=""
REMOTE_USER="root"
USE_WIREGUARD=false

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# ==================== Helper Functions ====================

log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

check_root() {
    if [[ $EUID -ne 0 && -z "$REMOTE_HOST" ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

detect_os() {
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        OS=$ID
        OS_VERSION=$VERSION_ID
        log_info "Detected OS: $OS $OS_VERSION"
    else
        log_error "Cannot detect OS"
        exit 1
    fi
}

install_dependencies() {
    log_info "Installing system dependencies..."

    case "$OS" in
        ubuntu|debian)
            apt-get update -qq
            apt-get install -y -qq wget curl tar adduser libfontconfig1 apt-transport-https software-properties-common
            ;;
        centos|rhel|rocky|almalinux)
            yum install -y -q wget curl tar fontconfig
            ;;
        *)
            log_error "Unsupported OS: $OS"
            exit 1
            ;;
    esac
}

create_system_user() {
    local username=$1
    if ! id "$username" &>/dev/null; then
        log_info "Creating system user: $username"
        useradd --system --no-create-home --shell /bin/false "$username" || true
    fi
}

# ==================== Prometheus Installation ====================

install_prometheus() {
    log_info "Installing Prometheus $PROMETHEUS_VERSION..."

    local prometheus_dir="$INSTALL_DIR/prometheus"
    local arch="linux-amd64"

    # Download if not exists or version changed
    if [[ ! -f "$prometheus_dir/prometheus" ]] || ! "$prometheus_dir/prometheus" --version 2>&1 | grep -q "$PROMETHEUS_VERSION"; then
        log_info "Downloading Prometheus..."
        local download_url="https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/prometheus-${PROMETHEUS_VERSION}.${arch}.tar.gz"

        cd /tmp
        wget -q "$download_url" -O prometheus.tar.gz || {
            log_error "Failed to download Prometheus"
            return 1
        }

        tar xzf prometheus.tar.gz

        # Install
        rm -rf "$prometheus_dir"
        mkdir -p "$prometheus_dir"
        cp -r "prometheus-${PROMETHEUS_VERSION}.${arch}"/* "$prometheus_dir/"

        # Create data directory
        mkdir -p "$DATA_DIR/prometheus"
        create_system_user prometheus
        chown -R prometheus:prometheus "$DATA_DIR/prometheus"

        # Cleanup
        rm -rf "prometheus-${PROMETHEUS_VERSION}.${arch}" prometheus.tar.gz

        log_info "Prometheus installed to $prometheus_dir"
    else
        log_info "Prometheus $PROMETHEUS_VERSION already installed"
    fi
}

configure_prometheus() {
    log_info "Configuring Prometheus..."

    local config_file="$CONFIG_DIR/prometheus/prometheus.yml"
    mkdir -p "$(dirname "$config_file")"

    cat > "$config_file" <<EOF
# Prometheus configuration
# Generated by setup_monitoring.sh

global:
  scrape_interval: ${PROMETHEUS_SCRAPE_INTERVAL}
  evaluation_interval: ${PROMETHEUS_SCRAPE_INTERVAL}
  external_labels:
    monitor: 'clippyfront'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['localhost:9093']

# Rule files (for alerts)
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:${PROMETHEUS_PORT}']

  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:${NODE_EXPORTER_PORT}']

  # ClippyFront application metrics
  - job_name: 'clippyfront'
    static_configs:
      - targets: ['localhost:${APP_METRICS_PORT}']
    metrics_path: '/metrics'

  # Redis metrics (if redis_exporter installed)
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']

  # PostgreSQL metrics (if postgres_exporter installed)
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:${POSTGRES_EXPORTER_PORT}']

  # Celery worker metrics (if exposed)
  - job_name: 'celery'
    static_configs:
      - targets: ['localhost:8808']
EOF

    # Create rules directory
    mkdir -p "$CONFIG_DIR/prometheus/rules"

    # Create basic alert rules
    cat > "$CONFIG_DIR/prometheus/rules/alerts.yml" <<'EOF'
groups:
  - name: clippyfront_alerts
    interval: 30s
    rules:
      # Instance down
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} has been down for more than 5 minutes."

      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% for 10 minutes."

      # High memory usage
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 90% for 10 minutes."

      # High disk usage
      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 85
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage on {{ $labels.instance }}"
          description: "Disk usage is above 85% on {{ $labels.mountpoint }}."
EOF

    log_info "Prometheus configuration written to $config_file"
}

create_prometheus_systemd() {
    log_info "Creating Prometheus systemd service..."

    cat > /etc/systemd/system/prometheus.service <<EOF
[Unit]
Description=Prometheus
Documentation=https://prometheus.io/docs/introduction/overview/
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=prometheus
Group=prometheus
ExecStart=${INSTALL_DIR}/prometheus/prometheus \\
  --config.file=${CONFIG_DIR}/prometheus/prometheus.yml \\
  --storage.tsdb.path=${DATA_DIR}/prometheus \\
  --storage.tsdb.retention.time=${PROMETHEUS_RETENTION} \\
  --web.console.templates=${INSTALL_DIR}/prometheus/consoles \\
  --web.console.libraries=${INSTALL_DIR}/prometheus/console_libraries \\
  --web.listen-address=0.0.0.0:${PROMETHEUS_PORT}

Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable prometheus
    systemctl restart prometheus

    log_info "Prometheus service started on port $PROMETHEUS_PORT"
}

# ==================== Node Exporter Installation ====================

install_node_exporter() {
    log_info "Installing Node Exporter $NODE_EXPORTER_VERSION..."

    local exporter_dir="$INSTALL_DIR/node_exporter"
    local arch="linux-amd64"

    if [[ ! -f "$exporter_dir/node_exporter" ]] || ! "$exporter_dir/node_exporter" --version 2>&1 | grep -q "$NODE_EXPORTER_VERSION"; then
        log_info "Downloading Node Exporter..."
        local download_url="https://github.com/prometheus/node_exporter/releases/download/v${NODE_EXPORTER_VERSION}/node_exporter-${NODE_EXPORTER_VERSION}.${arch}.tar.gz"

        cd /tmp
        wget -q "$download_url" -O node_exporter.tar.gz || {
            log_error "Failed to download Node Exporter"
            return 1
        }

        tar xzf node_exporter.tar.gz

        # Install
        rm -rf "$exporter_dir"
        mkdir -p "$exporter_dir"
        cp "node_exporter-${NODE_EXPORTER_VERSION}.${arch}/node_exporter" "$exporter_dir/"

        # Cleanup
        rm -rf "node_exporter-${NODE_EXPORTER_VERSION}.${arch}" node_exporter.tar.gz

        log_info "Node Exporter installed to $exporter_dir"
    else
        log_info "Node Exporter $NODE_EXPORTER_VERSION already installed"
    fi
}

create_node_exporter_systemd() {
    log_info "Creating Node Exporter systemd service..."

    create_system_user node_exporter

    cat > /etc/systemd/system/node_exporter.service <<EOF
[Unit]
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=node_exporter
Group=node_exporter
ExecStart=${INSTALL_DIR}/node_exporter/node_exporter \\
  --web.listen-address=:${NODE_EXPORTER_PORT}

Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable node_exporter
    systemctl restart node_exporter

    log_info "Node Exporter service started on port $NODE_EXPORTER_PORT"
}

# ==================== Grafana Installation ====================

install_grafana() {
    log_info "Installing Grafana $GRAFANA_VERSION..."

    case "$OS" in
        ubuntu|debian)
            # Add Grafana APT repository
            if [[ ! -f /etc/apt/sources.list.d/grafana.list ]]; then
                wget -q -O /usr/share/keyrings/grafana.key https://apt.grafana.com/gpg.key
                echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" | tee /etc/apt/sources.list.d/grafana.list
                apt-get update -qq
            fi
            apt-get install -y -qq grafana
            ;;
        centos|rhel|rocky|almalinux)
            # Add Grafana YUM repository
            if [[ ! -f /etc/yum.repos.d/grafana.repo ]]; then
                cat > /etc/yum.repos.d/grafana.repo <<'REPO'
[grafana]
name=grafana
baseurl=https://rpm.grafana.com
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://rpm.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
REPO
            fi
            yum install -y -q grafana
            ;;
    esac

    log_info "Grafana installed"
}

configure_grafana() {
    log_info "Configuring Grafana..."

    local config_file="/etc/grafana/grafana.ini"

    # Prompt for admin password if not set
    if [[ -z "$GRAFANA_ADMIN_PASSWORD" ]]; then
        read -rsp "Enter Grafana admin password (leave empty to keep default 'admin'): " GRAFANA_ADMIN_PASSWORD
        echo
        if [[ -z "$GRAFANA_ADMIN_PASSWORD" ]]; then
            GRAFANA_ADMIN_PASSWORD="admin"
            log_warn "Using default password 'admin'. Change this after first login!"
        fi
    fi

    # Update Grafana configuration
    sed -i "s/^;http_port = .*/http_port = $GRAFANA_PORT/" "$config_file"
    sed -i "s/^;admin_user = .*/admin_user = $GRAFANA_ADMIN_USER/" "$config_file"
    sed -i "s/^;admin_password = .*/admin_password = $GRAFANA_ADMIN_PASSWORD/" "$config_file"

    # Create provisioning directories
    mkdir -p /etc/grafana/provisioning/datasources
    mkdir -p /etc/grafana/provisioning/dashboards

    # Provision Prometheus datasource
    cat > /etc/grafana/provisioning/datasources/prometheus.yml <<EOF
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:${PROMETHEUS_PORT}
    isDefault: true
    editable: true
EOF

    # Provision dashboard provider
    cat > /etc/grafana/provisioning/dashboards/default.yml <<EOF
apiVersion: 1

providers:
  - name: 'default'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
EOF

    # Create dashboards directory
    mkdir -p /var/lib/grafana/dashboards

    # Download ClippyFront dashboard template (example)
    log_info "Creating ClippyFront dashboard..."
    create_clippyfront_dashboard

    log_info "Grafana configuration complete"
}

create_clippyfront_dashboard() {
    cat > /var/lib/grafana/dashboards/clippyfront.json <<'EOF'
{
  "dashboard": {
    "title": "ClippyFront Monitoring",
    "panels": [
      {
        "title": "CPU Usage",
        "targets": [
          {
            "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
          }
        ],
        "type": "graph"
      },
      {
        "title": "Memory Usage",
        "targets": [
          {
            "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100"
          }
        ],
        "type": "graph"
      },
      {
        "title": "Disk Usage",
        "targets": [
          {
            "expr": "100 - ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes)"
          }
        ],
        "type": "graph"
      },
      {
        "title": "HTTP Requests Rate",
        "targets": [
          {
            "expr": "rate(flask_http_request_total[5m])"
          }
        ],
        "type": "graph"
      }
    ],
    "refresh": "30s",
    "schemaVersion": 16,
    "version": 0
  }
}
EOF
}

start_grafana() {
    log_info "Starting Grafana..."

    systemctl daemon-reload
    systemctl enable grafana-server
    systemctl restart grafana-server

    log_info "Grafana service started on port $GRAFANA_PORT"
}

# ==================== Firewall Configuration ====================

configure_firewall() {
    log_info "Configuring firewall rules..."

    if command -v ufw &>/dev/null; then
        # UFW (Ubuntu/Debian)
        ufw allow "$PROMETHEUS_PORT/tcp" comment "Prometheus"
        ufw allow "$GRAFANA_PORT/tcp" comment "Grafana"
        ufw allow "$NODE_EXPORTER_PORT/tcp" comment "Node Exporter"
        log_info "UFW rules added"
    elif command -v firewall-cmd &>/dev/null; then
        # firewalld (RHEL/CentOS)
        firewall-cmd --permanent --add-port="$PROMETHEUS_PORT/tcp"
        firewall-cmd --permanent --add-port="$GRAFANA_PORT/tcp"
        firewall-cmd --permanent --add-port="$NODE_EXPORTER_PORT/tcp"
        firewall-cmd --reload
        log_info "firewalld rules added"
    else
        log_warn "No supported firewall found. Please configure manually."
    fi
}

# ==================== Remote Execution ====================

execute_remotely() {
    local script_path="$0"
    local remote_args=""

    # Build arguments without --remote flags
    for arg in "$@"; do
        if [[ "$arg" != "--remote" && "$arg" != "$REMOTE_HOST" && "$arg" != "--user" && "$arg" != "$REMOTE_USER" ]]; then
            remote_args="$remote_args $arg"
        fi
    done

    log_info "Executing on remote host: $REMOTE_USER@$REMOTE_HOST"

    # Copy script to remote
    scp "$script_path" "$REMOTE_USER@$REMOTE_HOST:/tmp/setup_monitoring.sh"

    # Execute remotely
    ssh "$REMOTE_USER@$REMOTE_HOST" "bash /tmp/setup_monitoring.sh $remote_args"

    # Cleanup
    ssh "$REMOTE_USER@$REMOTE_HOST" "rm /tmp/setup_monitoring.sh"

    log_info "Remote execution complete"
}

# ==================== Main Installation ====================

main() {
    log_info "Starting monitoring stack installation..."
    log_info "Prometheus: v$PROMETHEUS_VERSION, Grafana: v$GRAFANA_VERSION"

    check_root
    detect_os
    install_dependencies

    # Install components
    install_prometheus
    configure_prometheus
    create_prometheus_systemd

    install_node_exporter
    create_node_exporter_systemd

    install_grafana
    configure_grafana
    start_grafana

    configure_firewall

    # Summary
    log_info "======================================"
    log_info "Monitoring stack installation complete!"
    log_info "======================================"
    echo
    log_info "Access URLs:"
    log_info "  Prometheus: http://localhost:$PROMETHEUS_PORT"
    log_info "  Grafana:    http://localhost:$GRAFANA_PORT"
    log_info "  Node Exporter: http://localhost:$NODE_EXPORTER_PORT/metrics"
    echo
    log_info "Grafana login:"
    log_info "  Username: $GRAFANA_ADMIN_USER"
    log_info "  Password: $GRAFANA_ADMIN_PASSWORD"
    echo
    log_info "To update configuration, edit:"
    log_info "  Prometheus: $CONFIG_DIR/prometheus/prometheus.yml"
    log_info "  Grafana:    /etc/grafana/grafana.ini"
    echo
    log_info "Service commands:"
    log_info "  sudo systemctl status prometheus"
    log_info "  sudo systemctl status grafana-server"
    log_info "  sudo systemctl status node_exporter"
    echo
    log_warn "Remember to change the Grafana admin password after first login!"
}

# ==================== CLI Argument Parsing ====================

while [[ $# -gt 0 ]]; do
    case $1 in
        --remote)
            REMOTE_HOST="$2"
            shift 2
            ;;
        --user)
            REMOTE_USER="$2"
            shift 2
            ;;
        --prometheus-version)
            PROMETHEUS_VERSION="$2"
            shift 2
            ;;
        --grafana-version)
            GRAFANA_VERSION="$2"
            shift 2
            ;;
        --prometheus-port)
            PROMETHEUS_PORT="$2"
            shift 2
            ;;
        --grafana-port)
            GRAFANA_PORT="$2"
            shift 2
            ;;
        --help)
            echo "Usage: $0 [OPTIONS]"
            echo
            echo "Options:"
            echo "  --remote <host>              Execute on remote host via SSH"
            echo "  --user <username>            Remote SSH user (default: root)"
            echo "  --prometheus-version <ver>   Prometheus version (default: $PROMETHEUS_VERSION)"
            echo "  --grafana-version <ver>      Grafana version (default: $GRAFANA_VERSION)"
            echo "  --prometheus-port <port>     Prometheus port (default: $PROMETHEUS_PORT)"
            echo "  --grafana-port <port>        Grafana port (default: $GRAFANA_PORT)"
            echo
            echo "Environment variables:"
            echo "  GRAFANA_ADMIN_PASSWORD       Set Grafana admin password"
            echo "  INSTALL_DIR                  Installation directory (default: /opt)"
            echo "  DATA_DIR                     Data directory (default: /var/lib)"
            echo
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Execute main or remotely
if [[ -n "$REMOTE_HOST" ]]; then
    execute_remotely "$@"
else
    main
fi
